// AiTopRll_.c created by MKNTRLL Tue Apr 22 23:34:06 2008
#include "stdafx.h"
// **********
// DO NOT EDIT THIS FILE!
// (It will be overwritten the next
// time you run MKNTRLL).
// ****[Made By JackyBoy]********

#include <windows.h>
#include "ntrll.h"

static char *VOSfuncName[] =
	{
	"cksent",
	"getpid",
	"suspend",
	"suspterm",
	"wakeup",
	"hangup",
	"voslog",
	"vid_write",
	"deventf",
	"ueventf",
	"hangup_t",
	"dtasknotify",
	"settaskvar",
	"gettaskvar",
	};

#define NrVosFuncs (sizeof(VOSfuncName)/sizeof(VOSfuncName[0]))

FARPROC fpVOSfunc_[NrVosFuncs];

static void NotImplemented()
	{
	MessageBox(NULL, "RLL needs newer version of VOS", "VOS RLL",
	  MB_ICONSTOP | MB_OK);
	return;
	}
static HINSTANCE hVOSDLL;
static LPSTR pszVersion = __TIME__;

static FUNCINFO FuncInfo[] = 
	{
	ENTRY_FUNC, "vosStart", (FARPROC) 0x6469,
	EXIT_FUNC, "vosExit", (FARPROC) 0xe0f4,
	};

DLLEXPORT DWORD RLLInfo(LPSTR pszVOSDLL, LPWORD lpNrFuncs,
  LPFUNCINFO *lpFuncInfo, LPSTR pszVer)
	{
	int i;
	*lpNrFuncs = 2;
	*lpFuncInfo = FuncInfo;
	strncpy(pszVer, pszVersion, 13);
	pszVer[13] = 0;

	if(!pszVOSDLL)
		return 0;

	hVOSDLL = LoadLibrary(pszVOSDLL);
	if(hVOSDLL == NULL)
		return 2;

	for (i = 0; i < NrVosFuncs; i++)
		{
		fpVOSfunc_[i] = GetProcAddress(hVOSDLL, VOSfuncName[i]);
		if(fpVOSfunc_[i] == NULL)
			fpVOSfunc_[i] = (FARPROC) NotImplemented;
		}

	return 0;
	}
