/* soapH.h
   Generated by gSOAP 2.7.10 from aitop.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns1__sendnote
#define SOAP_TYPE_ns1__sendnote (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sendnote(struct soap*, struct ns1__sendnote *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sendnote(struct soap*, const struct ns1__sendnote *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sendnote(struct soap*, const struct ns1__sendnote *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sendnote(struct soap*, const char*, int, const struct ns1__sendnote *, const char*);
SOAP_FMAC3 struct ns1__sendnote * SOAP_FMAC4 soap_get_ns1__sendnote(struct soap*, struct ns1__sendnote *, const char*, const char*);
SOAP_FMAC3 struct ns1__sendnote * SOAP_FMAC4 soap_in_ns1__sendnote(struct soap*, const char*, struct ns1__sendnote *, const char*);
SOAP_FMAC5 struct ns1__sendnote * SOAP_FMAC6 soap_new_ns1__sendnote(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sendnote(struct soap*, struct ns1__sendnote*);
SOAP_FMAC3 struct ns1__sendnote * SOAP_FMAC4 soap_instantiate_ns1__sendnote(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sendnote(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__sendnoteResponse
#define SOAP_TYPE_ns1__sendnoteResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sendnoteResponse(struct soap*, struct ns1__sendnoteResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sendnoteResponse(struct soap*, const struct ns1__sendnoteResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sendnoteResponse(struct soap*, const struct ns1__sendnoteResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sendnoteResponse(struct soap*, const char*, int, const struct ns1__sendnoteResponse *, const char*);
SOAP_FMAC3 struct ns1__sendnoteResponse * SOAP_FMAC4 soap_get_ns1__sendnoteResponse(struct soap*, struct ns1__sendnoteResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__sendnoteResponse * SOAP_FMAC4 soap_in_ns1__sendnoteResponse(struct soap*, const char*, struct ns1__sendnoteResponse *, const char*);
SOAP_FMAC5 struct ns1__sendnoteResponse * SOAP_FMAC6 soap_new_ns1__sendnoteResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sendnoteResponse(struct soap*, struct ns1__sendnoteResponse*);
SOAP_FMAC3 struct ns1__sendnoteResponse * SOAP_FMAC4 soap_instantiate_ns1__sendnoteResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sendnoteResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__sendFailed
#define SOAP_TYPE_ns1__sendFailed (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sendFailed(struct soap*, struct ns1__sendFailed *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sendFailed(struct soap*, const struct ns1__sendFailed *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sendFailed(struct soap*, const struct ns1__sendFailed *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sendFailed(struct soap*, const char*, int, const struct ns1__sendFailed *, const char*);
SOAP_FMAC3 struct ns1__sendFailed * SOAP_FMAC4 soap_get_ns1__sendFailed(struct soap*, struct ns1__sendFailed *, const char*, const char*);
SOAP_FMAC3 struct ns1__sendFailed * SOAP_FMAC4 soap_in_ns1__sendFailed(struct soap*, const char*, struct ns1__sendFailed *, const char*);
SOAP_FMAC5 struct ns1__sendFailed * SOAP_FMAC6 soap_new_ns1__sendFailed(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sendFailed(struct soap*, struct ns1__sendFailed*);
SOAP_FMAC3 struct ns1__sendFailed * SOAP_FMAC4 soap_instantiate_ns1__sendFailed(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sendFailed(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__sendFailedResponse
#define SOAP_TYPE_ns1__sendFailedResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sendFailedResponse(struct soap*, struct ns1__sendFailedResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sendFailedResponse(struct soap*, const struct ns1__sendFailedResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sendFailedResponse(struct soap*, const struct ns1__sendFailedResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sendFailedResponse(struct soap*, const char*, int, const struct ns1__sendFailedResponse *, const char*);
SOAP_FMAC3 struct ns1__sendFailedResponse * SOAP_FMAC4 soap_get_ns1__sendFailedResponse(struct soap*, struct ns1__sendFailedResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__sendFailedResponse * SOAP_FMAC4 soap_in_ns1__sendFailedResponse(struct soap*, const char*, struct ns1__sendFailedResponse *, const char*);
SOAP_FMAC5 struct ns1__sendFailedResponse * SOAP_FMAC6 soap_new_ns1__sendFailedResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sendFailedResponse(struct soap*, struct ns1__sendFailedResponse*);
SOAP_FMAC3 struct ns1__sendFailedResponse * SOAP_FMAC4 soap_instantiate_ns1__sendFailedResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sendFailedResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__send__
#define SOAP_TYPE_ns1__send__ (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__send__(struct soap*, struct ns1__send__ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__send__(struct soap*, const struct ns1__send__ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__send__(struct soap*, const struct ns1__send__ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__send__(struct soap*, const char*, int, const struct ns1__send__ *, const char*);
SOAP_FMAC3 struct ns1__send__ * SOAP_FMAC4 soap_get_ns1__send__(struct soap*, struct ns1__send__ *, const char*, const char*);
SOAP_FMAC3 struct ns1__send__ * SOAP_FMAC4 soap_in_ns1__send__(struct soap*, const char*, struct ns1__send__ *, const char*);
SOAP_FMAC5 struct ns1__send__ * SOAP_FMAC6 soap_new_ns1__send__(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__send__(struct soap*, struct ns1__send__*);
SOAP_FMAC3 struct ns1__send__ * SOAP_FMAC4 soap_instantiate_ns1__send__(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__send__(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__send__Response
#define SOAP_TYPE_ns1__send__Response (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__send__Response(struct soap*, struct ns1__send__Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__send__Response(struct soap*, const struct ns1__send__Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__send__Response(struct soap*, const struct ns1__send__Response *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__send__Response(struct soap*, const char*, int, const struct ns1__send__Response *, const char*);
SOAP_FMAC3 struct ns1__send__Response * SOAP_FMAC4 soap_get_ns1__send__Response(struct soap*, struct ns1__send__Response *, const char*, const char*);
SOAP_FMAC3 struct ns1__send__Response * SOAP_FMAC4 soap_in_ns1__send__Response(struct soap*, const char*, struct ns1__send__Response *, const char*);
SOAP_FMAC5 struct ns1__send__Response * SOAP_FMAC6 soap_new_ns1__send__Response(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__send__Response(struct soap*, struct ns1__send__Response*);
SOAP_FMAC3 struct ns1__send__Response * SOAP_FMAC4 soap_instantiate_ns1__send__Response(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__send__Response(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__send_
#define SOAP_TYPE_ns1__send_ (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__send_(struct soap*, struct ns1__send_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__send_(struct soap*, const struct ns1__send_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__send_(struct soap*, const struct ns1__send_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__send_(struct soap*, const char*, int, const struct ns1__send_ *, const char*);
SOAP_FMAC3 struct ns1__send_ * SOAP_FMAC4 soap_get_ns1__send_(struct soap*, struct ns1__send_ *, const char*, const char*);
SOAP_FMAC3 struct ns1__send_ * SOAP_FMAC4 soap_in_ns1__send_(struct soap*, const char*, struct ns1__send_ *, const char*);
SOAP_FMAC5 struct ns1__send_ * SOAP_FMAC6 soap_new_ns1__send_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__send_(struct soap*, struct ns1__send_*);
SOAP_FMAC3 struct ns1__send_ * SOAP_FMAC4 soap_instantiate_ns1__send_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__send_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__send_Response
#define SOAP_TYPE_ns1__send_Response (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__send_Response(struct soap*, struct ns1__send_Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__send_Response(struct soap*, const struct ns1__send_Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__send_Response(struct soap*, const struct ns1__send_Response *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__send_Response(struct soap*, const char*, int, const struct ns1__send_Response *, const char*);
SOAP_FMAC3 struct ns1__send_Response * SOAP_FMAC4 soap_get_ns1__send_Response(struct soap*, struct ns1__send_Response *, const char*, const char*);
SOAP_FMAC3 struct ns1__send_Response * SOAP_FMAC4 soap_in_ns1__send_Response(struct soap*, const char*, struct ns1__send_Response *, const char*);
SOAP_FMAC5 struct ns1__send_Response * SOAP_FMAC6 soap_new_ns1__send_Response(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__send_Response(struct soap*, struct ns1__send_Response*);
SOAP_FMAC3 struct ns1__send_Response * SOAP_FMAC4 soap_instantiate_ns1__send_Response(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__send_Response(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__send
#define SOAP_TYPE_ns1__send (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__send(struct soap*, struct ns1__send *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__send(struct soap*, const struct ns1__send *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__send(struct soap*, const struct ns1__send *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__send(struct soap*, const char*, int, const struct ns1__send *, const char*);
SOAP_FMAC3 struct ns1__send * SOAP_FMAC4 soap_get_ns1__send(struct soap*, struct ns1__send *, const char*, const char*);
SOAP_FMAC3 struct ns1__send * SOAP_FMAC4 soap_in_ns1__send(struct soap*, const char*, struct ns1__send *, const char*);
SOAP_FMAC5 struct ns1__send * SOAP_FMAC6 soap_new_ns1__send(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__send(struct soap*, struct ns1__send*);
SOAP_FMAC3 struct ns1__send * SOAP_FMAC4 soap_instantiate_ns1__send(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__send(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__sendResponse
#define SOAP_TYPE_ns1__sendResponse (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__sendResponse(struct soap*, struct ns1__sendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__sendResponse(struct soap*, const struct ns1__sendResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__sendResponse(struct soap*, const struct ns1__sendResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__sendResponse(struct soap*, const char*, int, const struct ns1__sendResponse *, const char*);
SOAP_FMAC3 struct ns1__sendResponse * SOAP_FMAC4 soap_get_ns1__sendResponse(struct soap*, struct ns1__sendResponse *, const char*, const char*);
SOAP_FMAC3 struct ns1__sendResponse * SOAP_FMAC4 soap_in_ns1__sendResponse(struct soap*, const char*, struct ns1__sendResponse *, const char*);
SOAP_FMAC5 struct ns1__sendResponse * SOAP_FMAC6 soap_new_ns1__sendResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__sendResponse(struct soap*, struct ns1__sendResponse*);
SOAP_FMAC3 struct ns1__sendResponse * SOAP_FMAC4 soap_instantiate_ns1__sendResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__sendResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
